"""Public core-domain API."""

from .enums import (
    AttentionMode,
    FitMode,
    MediaType,
    PermissionStatus,
    ProjectState,
    ReviewPriority,
    ReviewStatus,
)
from .ids import EntityKind, RegistryKey, new_entity_id, require_entity_id
from .models import (
    Asset,
    AssetRef,
    AudioTrack,
    LanguageTag,
    MotionSpec,
    NormalizedPoint,
    NormalizedRect,
    OutputProfile,
    Overlay,
    Project,
    ReviewSuggestion,
    ReviewTask,
    SafeZone,
    Scene,
    SourceRecord,
    TemplateRef,
    TransitionSpec,
    Variant,
)
from .serialization import (
    dump_json,
    dump_yaml,
    load_json,
    load_model,
    load_yaml,
    save_model,
)
from .versioning import (
    CURRENT_SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    is_supported_schema_version,
)

__all__ = [
    "Asset",
    "AssetRef",
    "AttentionMode",
    "AudioTrack",
    "CURRENT_SCHEMA_VERSION",
    "EntityKind",
    "FitMode",
    "LanguageTag",
    "MediaType",
    "MotionSpec",
    "NormalizedPoint",
    "NormalizedRect",
    "OutputProfile",
    "Overlay",
    "PermissionStatus",
    "Project",
    "ProjectState",
    "RegistryKey",
    "ReviewPriority",
    "ReviewStatus",
    "ReviewSuggestion",
    "ReviewTask",
    "SUPPORTED_SCHEMA_VERSIONS",
    "SafeZone",
    "Scene",
    "SourceRecord",
    "TemplateRef",
    "TransitionSpec",
    "Variant",
    "dump_json",
    "dump_yaml",
    "is_supported_schema_version",
    "load_json",
    "load_model",
    "load_yaml",
    "new_entity_id",
    "require_entity_id",
    "save_model",
]
