"""Optional provider boundaries for Content Forge."""

from .chatgpt_web_adapter import ChatGPTWebAdapterLLMProvider
from .llm import (
    ClassificationRequest,
    ClassificationResult,
    HookRequest,
    HookSuggestions,
    LLMExecutionError,
    LLMInvocationEvidence,
    LLMProvider,
    LLMProviderError,
    LLMProviderHealth,
    LLMResponseError,
    LLMUnavailableError,
    MetadataCandidate,
    MetadataRequest,
    MetadataSuggestions,
    TextCleanupRequest,
    TextCleanupResult,
    TranslationRequest,
    TranslationResult,
    build_task_prompt,
    replace_provider_suggestions,
    semantic_request_digest,
    strict_json_object,
    to_review_suggestions,
)

__all__ = [
    "ChatGPTWebAdapterLLMProvider",
    "ClassificationRequest",
    "ClassificationResult",
    "HookRequest",
    "HookSuggestions",
    "LLMExecutionError",
    "LLMInvocationEvidence",
    "LLMProvider",
    "LLMProviderError",
    "LLMProviderHealth",
    "LLMResponseError",
    "LLMUnavailableError",
    "MetadataCandidate",
    "MetadataRequest",
    "MetadataSuggestions",
    "TextCleanupRequest",
    "TextCleanupResult",
    "TranslationRequest",
    "TranslationResult",
    "build_task_prompt",
    "replace_provider_suggestions",
    "semantic_request_digest",
    "strict_json_object",
    "to_review_suggestions",
]
