"""Application services between transport clients and Content Forge core/runtime."""

from .auth import AuthManager, AuthenticationError, IssuedSession
from .dialogue import (
    CharacterRecord,
    DialogueAssignment,
    DialogueAssignmentSuggestion,
    DialogueConflictError,
    DialogueError,
    DialogueLine,
    DialogueNotFoundError,
    DialogueValidationError,
    ProjectDialogueManifest,
    SceneDialogue,
    SceneFocusHint,
    dialogue_manifest,
    scene_dialogue_digest,
)
from .dialogue_pr19_integrity import DialogueWorkflow
from .inbox import InboxError, InboxService, UploadTooLargeError
from .models import (
    AuthSession,
    InboxIntake,
    IntakeKind,
    IntakeState,
    PairingChallenge,
    PreparationState,
)
from .panel_ocr import (
    PanelOCRConflictError,
    PanelOCRError,
    PanelOCRNotFoundError,
    PanelOCRPreparation,
    PanelOCRValidationError,
    PanelOCRWorkflow,
    PanelTextExtraction,
    PanelTextRegion,
    panel_extraction_digest,
    prepare_panel_ocr,
)
from .repository import ApplicationRepository
from .review import (
    ReviewConflictError,
    ReviewError,
    ReviewNotFoundError,
    ReviewNotReadyError,
    ReviewRenderError,
    ReviewValidationError,
)
from .tts import (
    LineTTSSettings,
    LineTTSWorkflow,
    ProjectTTSManifest,
    SynthesizedDialogueLine,
    TTSConflictError,
    TTSError,
    TTSNotFoundError,
    TTSSynthesisError,
    TTSValidationError,
    tts_manifest,
)
from .voice_cast import (
    CharacterCastBinding,
    ProjectVoiceCastManifest,
    ResolvedLineVoice,
    VoiceCastConflictError,
    VoiceCastDefinition,
    VoiceCastError,
    VoiceCastNotFoundError,
    VoiceCastRegistry,
    VoiceCastRevision,
    VoiceCastUnavailableError,
    VoiceCastValidationError,
    VoiceCastWorkflow,
    voice_cast_manifest,
)
from .voiced_story import (
    ProjectVoicedStoryManifest,
    TimedTextCue,
    VoicedStoryConflictError,
    VoicedStoryError,
    VoicedStoryLine,
    VoicedStoryNotFoundError,
    VoicedStoryNotReadyError,
    VoicedStoryScene,
    VoicedStoryTimingPolicy,
    VoicedStoryValidationError,
    VoicedStoryWorkflow,
    voiced_story_manifest,
)
# Install the PR17 startup ownership boundary in place before exposing the existing
# seventh-pass ReviewService class. This preserves all public class identities.
from . import review_pr17_hardening as _review_pr17_hardening  # noqa: F401
from .review_seventh_hardening import ReviewService

__all__ = [
    "ApplicationRepository",
    "AuthManager",
    "AuthenticationError",
    "AuthSession",
    "CharacterCastBinding",
    "CharacterRecord",
    "DialogueAssignment",
    "DialogueAssignmentSuggestion",
    "DialogueConflictError",
    "DialogueError",
    "DialogueLine",
    "DialogueNotFoundError",
    "DialogueValidationError",
    "DialogueWorkflow",
    "InboxError",
    "InboxIntake",
    "InboxService",
    "IntakeKind",
    "IntakeState",
    "IssuedSession",
    "LineTTSSettings",
    "LineTTSWorkflow",
    "PairingChallenge",
    "PanelOCRConflictError",
    "PanelOCRError",
    "PanelOCRNotFoundError",
    "PanelOCRPreparation",
    "PanelOCRValidationError",
    "PanelOCRWorkflow",
    "PanelTextExtraction",
    "PanelTextRegion",
    "PreparationState",
    "ProjectDialogueManifest",
    "ProjectTTSManifest",
    "ProjectVoiceCastManifest",
    "ProjectVoicedStoryManifest",
    "ResolvedLineVoice",
    "ReviewConflictError",
    "ReviewError",
    "ReviewNotFoundError",
    "ReviewNotReadyError",
    "ReviewRenderError",
    "ReviewService",
    "ReviewValidationError",
    "SceneDialogue",
    "SceneFocusHint",
    "SynthesizedDialogueLine",
    "TTSConflictError",
    "TTSError",
    "TTSNotFoundError",
    "TTSSynthesisError",
    "TTSValidationError",
    "TimedTextCue",
    "UploadTooLargeError",
    "VoiceCastConflictError",
    "VoiceCastDefinition",
    "VoiceCastError",
    "VoiceCastNotFoundError",
    "VoiceCastRegistry",
    "VoiceCastRevision",
    "VoiceCastUnavailableError",
    "VoiceCastValidationError",
    "VoiceCastWorkflow",
    "VoicedStoryConflictError",
    "VoicedStoryError",
    "VoicedStoryLine",
    "VoicedStoryNotFoundError",
    "VoicedStoryNotReadyError",
    "VoicedStoryScene",
    "VoicedStoryTimingPolicy",
    "VoicedStoryValidationError",
    "VoicedStoryWorkflow",
    "dialogue_manifest",
    "panel_extraction_digest",
    "prepare_panel_ocr",
    "scene_dialogue_digest",
    "tts_manifest",
    "voice_cast_manifest",
    "voiced_story_manifest",
]
