"""Storage-layer input and metadata records."""

from __future__ import annotations

from datetime import datetime, timezone

from pydantic import BaseModel, ConfigDict, Field, JsonValue, field_validator

from content_forge.core import (
    EntityKind,
    PermissionStatus,
    RegistryKey,
    new_entity_id,
    require_entity_id,
)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _aware(value: datetime) -> datetime:
    if value.tzinfo is None or value.utcoffset() is None:
        raise ValueError("datetime must be timezone-aware")
    return value


class StorageModel(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid", allow_inf_nan=False)


class SourceInput(StorageModel):
    """Provenance supplied at ingest before the immutable asset ID is known."""

    source_url: str | None = Field(default=None, max_length=4096)
    platform: str | None = Field(default=None, max_length=128)
    creator_name: str | None = Field(default=None, max_length=512)
    creator_handle: str | None = Field(default=None, max_length=512)
    original_title: str | None = Field(default=None, max_length=2048)
    collected_at: datetime = Field(default_factory=utc_now)
    credit_text: str | None = Field(default=None, max_length=2048)
    requires_credit: bool | None = None
    permission_status: PermissionStatus = PermissionStatus.UNKNOWN
    permission_note: str | None = Field(default=None, max_length=4096)
    notes: str | None = Field(default=None, max_length=8192)

    @field_validator("collected_at")
    @classmethod
    def validate_collected_at(cls, value: datetime) -> datetime:
        return _aware(value)


class StoredJob(StorageModel):
    """Small persistent queue metadata record; execution arrives in later PRs."""

    job_id: str = Field(default_factory=lambda: new_entity_id(EntityKind.JOB))
    project_id: str | None = None
    job_type: RegistryKey
    state: RegistryKey = "queued"
    payload: dict[str, JsonValue] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)

    @field_validator("job_id")
    @classmethod
    def validate_job_id(cls, value: str) -> str:
        return require_entity_id(value, EntityKind.JOB)

    @field_validator("project_id")
    @classmethod
    def validate_project_id(cls, value: str | None) -> str | None:
        if value is not None:
            return require_entity_id(value, EntityKind.PROJECT)
        return value

    @field_validator("created_at", "updated_at")
    @classmethod
    def validate_datetimes(cls, value: datetime) -> datetime:
        return _aware(value)


class DerivativeSlot(StorageModel):
    """Metadata placeholder for a thumbnail/proxy generated by a later milestone."""

    asset_id: str
    slot: RegistryKey
    storage_key: str | None = Field(default=None, min_length=1, max_length=1024)
    metadata: dict[str, JsonValue] = Field(default_factory=dict)
    updated_at: datetime = Field(default_factory=utc_now)

    @field_validator("asset_id")
    @classmethod
    def validate_asset_id(cls, value: str) -> str:
        return require_entity_id(value, EntityKind.ASSET)

    @field_validator("updated_at")
    @classmethod
    def validate_updated_at(cls, value: datetime) -> datetime:
        return _aware(value)
