"""Built-in and registered presentation templates."""

from .builtins import (
    BUILTIN_COMPONENT_VERSION,
    MEDIA_COMPONENT,
    NEUTRAL_FRAME_ASSET,
    NEUTRAL_FRAME_ASSET_ID,
    NEUTRAL_FRAME_ASSET_SHA256,
    NEUTRAL_SKIN,
    NEUTRAL_SKIN_ID,
    NEUTRAL_SKIN_VERSION,
    ORIGINAL_AUDIO_COMPONENT,
    TEXT_COMPONENT,
    compile_registered_hook_overlay,
    compile_registered_template,
    create_builtin_registries,
    hook_overlay_definition,
    resolve_registered_template,
)
from .components import (
    ARTIST_CREDIT_COMPONENT,
    ARTIST_CREDIT_COMPONENT_ID,
    AVATAR_COMPONENT,
    AVATAR_COMPONENT_ID,
    BLUR_REVEAL_COMPONENT,
    BLUR_REVEAL_COMPONENT_ID,
    COMMENT_CARD_COMPONENT,
    COMMENT_CARD_COMPONENT_ID,
    CROP_REVEAL_COMPONENT,
    CROP_REVEAL_COMPONENT_ID,
    KEN_BURNS_COMPONENT,
    KEN_BURNS_COMPONENT_ID,
    PAN_COMPONENT,
    PAN_COMPONENT_ID,
    PR13_COMPONENTS,
    PR13_COMPONENT_VERSION,
    REACTION_COMPONENT,
    REACTION_COMPONENT_ID,
    TRANSITION_COMPONENT,
    TRANSITION_COMPONENT_ID,
    WATERMARK_COMPONENT,
    WATERMARK_COMPONENT_ID,
    ComponentRuntimeError,
    artist_credit_overlay,
    aspect_safe_rect,
    avatar_overlay,
    blur_reveal_motion,
    bounded_text_overlay,
    comment_card_overlay,
    crop_reveal_motion,
    ken_burns_motion,
    pan_motion,
    reaction_overlay,
    simple_transition,
    watermark_overlay,
)
from .contracts import (
    ComponentDefinition,
    ComponentRef,
    SkinDefinition,
    SkinRef,
    TemplateAnchor,
    TemplateAssetDefinition,
    TemplateContractError,
    TemplateDefault,
    TemplateDefinition,
    TemplateSafeZone,
    TemplateSlot,
)
from .hook_overlay import (
    HOOK_OVERLAY_TEMPLATE_ID,
    HOOK_OVERLAY_TEMPLATE_VERSION,
    HookOverlayAssetResolver,
    HookOverlayConfig,
    HookOverlayTemplateError,
    resolve_hook_overlay,
)
from .initial_pack import (
    ART_STORY_TEMPLATE_ID,
    CONTENT_FRAME_TEMPLATE_ID,
    HOOK_TOPBAR_TEMPLATE_ID,
    INITIAL_TEMPLATE_IDS,
    INITIAL_TEMPLATE_VERSION,
    MEDIA_OVERLAY_COMPONENT,
    MEME_WHITE_HEADER_TEMPLATE_ID,
    PANEL_SEQUENCE_TEMPLATE_ID,
    REACTION_BOTTOM_TEMPLATE_ID,
    SOCIAL_POST_TEMPLATE_ID,
    SYNC_STACK_TEMPLATE_ID,
    InitialTemplateError,
    initial_template_definitions,
    resolve_panel_sequence,
)
from .initial_pack_runtime import (
    initial_template_registrations,
    resolve_art_story,
    resolve_content_frame,
    resolve_hook_topbar,
    resolve_meme_white_header,
    resolve_reaction_bottom,
    resolve_social_post,
    resolve_sync_stack,
)
from .plugins import (
    COMPONENT_ENTRY_POINT_GROUP,
    PLUGIN_ENTRY_POINT_GROUPS,
    SKIN_ENTRY_POINT_GROUP,
    TEMPLATE_ENTRY_POINT_GROUP,
    PluginCandidate,
    discover_plugin_candidates,
)
from .registry import (
    REGISTRY_EVIDENCE_PROPERTY,
    ComponentRegistry,
    DuplicateRegistryEntryError,
    RegistryBundle,
    RegistryError,
    RegistryReferenceError,
    SkinRegistry,
    TemplateAssetRegistry,
    TemplateRegistration,
    TemplateRegistry,
    TemplateResolutionRegistryError,
    UnknownRegistryEntryError,
)

compile_hook_overlay = compile_registered_hook_overlay

__all__ = [
    "ARTIST_CREDIT_COMPONENT", "ARTIST_CREDIT_COMPONENT_ID", "ART_STORY_TEMPLATE_ID",
    "AVATAR_COMPONENT", "AVATAR_COMPONENT_ID", "BLUR_REVEAL_COMPONENT",
    "BLUR_REVEAL_COMPONENT_ID", "BUILTIN_COMPONENT_VERSION", "COMMENT_CARD_COMPONENT",
    "COMMENT_CARD_COMPONENT_ID", "COMPONENT_ENTRY_POINT_GROUP", "CONTENT_FRAME_TEMPLATE_ID",
    "CROP_REVEAL_COMPONENT", "CROP_REVEAL_COMPONENT_ID", "ComponentDefinition",
    "ComponentRef", "ComponentRegistry", "ComponentRuntimeError",
    "DuplicateRegistryEntryError", "HOOK_OVERLAY_TEMPLATE_ID", "HOOK_OVERLAY_TEMPLATE_VERSION",
    "HOOK_TOPBAR_TEMPLATE_ID", "HookOverlayAssetResolver", "HookOverlayConfig",
    "HookOverlayTemplateError", "INITIAL_TEMPLATE_IDS", "INITIAL_TEMPLATE_VERSION",
    "InitialTemplateError", "KEN_BURNS_COMPONENT", "KEN_BURNS_COMPONENT_ID",
    "MEDIA_COMPONENT", "MEDIA_OVERLAY_COMPONENT", "MEME_WHITE_HEADER_TEMPLATE_ID",
    "NEUTRAL_FRAME_ASSET", "NEUTRAL_FRAME_ASSET_ID", "NEUTRAL_FRAME_ASSET_SHA256",
    "NEUTRAL_SKIN", "NEUTRAL_SKIN_ID", "NEUTRAL_SKIN_VERSION", "ORIGINAL_AUDIO_COMPONENT",
    "PANEL_SEQUENCE_TEMPLATE_ID", "PAN_COMPONENT", "PAN_COMPONENT_ID",
    "PLUGIN_ENTRY_POINT_GROUPS", "PR13_COMPONENTS", "PR13_COMPONENT_VERSION",
    "PluginCandidate", "REACTION_BOTTOM_TEMPLATE_ID", "REACTION_COMPONENT",
    "REACTION_COMPONENT_ID", "REGISTRY_EVIDENCE_PROPERTY", "RegistryBundle", "RegistryError",
    "RegistryReferenceError", "SKIN_ENTRY_POINT_GROUP", "SOCIAL_POST_TEMPLATE_ID",
    "SYNC_STACK_TEMPLATE_ID", "SkinDefinition", "SkinRef", "SkinRegistry",
    "TEMPLATE_ENTRY_POINT_GROUP", "TEXT_COMPONENT", "TRANSITION_COMPONENT",
    "TRANSITION_COMPONENT_ID", "TemplateAnchor", "TemplateAssetDefinition",
    "TemplateAssetRegistry", "TemplateContractError", "TemplateDefault", "TemplateDefinition",
    "TemplateRegistration", "TemplateRegistry", "TemplateResolutionRegistryError",
    "TemplateSafeZone", "TemplateSlot", "UnknownRegistryEntryError", "WATERMARK_COMPONENT",
    "WATERMARK_COMPONENT_ID", "artist_credit_overlay", "aspect_safe_rect", "avatar_overlay",
    "blur_reveal_motion", "bounded_text_overlay", "comment_card_overlay", "compile_hook_overlay",
    "compile_registered_template", "create_builtin_registries", "crop_reveal_motion",
    "discover_plugin_candidates", "hook_overlay_definition", "initial_template_definitions",
    "initial_template_registrations", "ken_burns_motion", "pan_motion", "reaction_overlay",
    "resolve_art_story", "resolve_content_frame", "resolve_hook_overlay", "resolve_hook_topbar",
    "resolve_meme_white_header", "resolve_panel_sequence", "resolve_reaction_bottom",
    "resolve_registered_template", "resolve_social_post", "resolve_sync_stack",
    "simple_transition", "watermark_overlay",
]
