"""Built-in and registered presentation templates."""

from .builtins import (
    BUILTIN_COMPONENT_VERSION,
    MEDIA_COMPONENT,
    NEUTRAL_FRAME_ASSET,
    NEUTRAL_FRAME_ASSET_ID,
    NEUTRAL_FRAME_ASSET_SHA256,
    NEUTRAL_SKIN,
    NEUTRAL_SKIN_ID,
    NEUTRAL_SKIN_VERSION,
    ORIGINAL_AUDIO_COMPONENT,
    TEXT_COMPONENT,
    compile_registered_hook_overlay,
    compile_registered_template,
    create_builtin_registries,
    hook_overlay_definition,
    resolve_registered_template,
)
from .contracts import (
    ComponentDefinition,
    ComponentRef,
    SkinDefinition,
    SkinRef,
    TemplateAnchor,
    TemplateAssetDefinition,
    TemplateContractError,
    TemplateDefault,
    TemplateDefinition,
    TemplateSafeZone,
    TemplateSlot,
)
from .hook_overlay import (
    HOOK_OVERLAY_TEMPLATE_ID,
    HOOK_OVERLAY_TEMPLATE_VERSION,
    HookOverlayAssetResolver,
    HookOverlayConfig,
    HookOverlayTemplateError,
    resolve_hook_overlay,
)
from .plugins import (
    COMPONENT_ENTRY_POINT_GROUP,
    PLUGIN_ENTRY_POINT_GROUPS,
    SKIN_ENTRY_POINT_GROUP,
    TEMPLATE_ENTRY_POINT_GROUP,
    PluginCandidate,
    discover_plugin_candidates,
)
from .registry import (
    REGISTRY_EVIDENCE_PROPERTY,
    ComponentRegistry,
    DuplicateRegistryEntryError,
    RegistryBundle,
    RegistryError,
    RegistryReferenceError,
    SkinRegistry,
    TemplateAssetRegistry,
    TemplateRegistration,
    TemplateRegistry,
    TemplateResolutionRegistryError,
    UnknownRegistryEntryError,
)

# Public compatibility entry point is registry-backed from PR11 onward. The low-level
# resolver module keeps its direct compiler only for internal semantic regression tests.
compile_hook_overlay = compile_registered_hook_overlay

__all__ = [
    "BUILTIN_COMPONENT_VERSION",
    "COMPONENT_ENTRY_POINT_GROUP",
    "ComponentDefinition",
    "ComponentRef",
    "ComponentRegistry",
    "DuplicateRegistryEntryError",
    "HOOK_OVERLAY_TEMPLATE_ID",
    "HOOK_OVERLAY_TEMPLATE_VERSION",
    "HookOverlayAssetResolver",
    "HookOverlayConfig",
    "HookOverlayTemplateError",
    "MEDIA_COMPONENT",
    "NEUTRAL_FRAME_ASSET",
    "NEUTRAL_FRAME_ASSET_ID",
    "NEUTRAL_FRAME_ASSET_SHA256",
    "NEUTRAL_SKIN",
    "NEUTRAL_SKIN_ID",
    "NEUTRAL_SKIN_VERSION",
    "ORIGINAL_AUDIO_COMPONENT",
    "PLUGIN_ENTRY_POINT_GROUPS",
    "PluginCandidate",
    "REGISTRY_EVIDENCE_PROPERTY",
    "RegistryBundle",
    "RegistryError",
    "RegistryReferenceError",
    "SKIN_ENTRY_POINT_GROUP",
    "SkinDefinition",
    "SkinRef",
    "SkinRegistry",
    "TEMPLATE_ENTRY_POINT_GROUP",
    "TEXT_COMPONENT",
    "TemplateAnchor",
    "TemplateAssetDefinition",
    "TemplateAssetRegistry",
    "TemplateContractError",
    "TemplateDefault",
    "TemplateDefinition",
    "TemplateRegistration",
    "TemplateRegistry",
    "TemplateResolutionRegistryError",
    "TemplateSafeZone",
    "TemplateSlot",
    "UnknownRegistryEntryError",
    "compile_hook_overlay",
    "compile_registered_template",
    "create_builtin_registries",
    "discover_plugin_candidates",
    "hook_overlay_definition",
    "resolve_hook_overlay",
    "resolve_registered_template",
]
